List<String> animallist = [
  "🐕 Dog",
  "🐈 Cat",
  "🐅 Tiger",
  "🐘 Elephant",
  "🐎 Horse",
  "🦁 Lion",
  "🐒 Monkey",
  "🐻 Bear",
  "🐬 Dolphin",
  "🐢 Turtle",
  "🐄 Cow",
  "🐝 Bee",
  "🦅 Eagle",
  "🦉 Owl",
  "🐺 Wolf",
  "🐧 Penguin",
  "🐍 Snake",
  "🐠 Fish",
  "🦄 Unicorn",
  "🐼 Panda",
];
List<String> list1 = [
  animallist[1],
  animallist[4],
  animallist[4],
  animallist[8],
  animallist[9],
  animallist[10],
  animallist[13],
  animallist[16],
  animallist[17],
  animallist[19],
];
List<String> list2 = [
  animallist[0],
  animallist[3],
  animallist[7],
  animallist[11],
  animallist[13],
  animallist[14],
  animallist[15],
  animallist[15],
  animallist[17],
  animallist[18],
];
List<String> list3 = [
  animallist[0],
  animallist[1],
  animallist[2],
  animallist[6],
  animallist[10],
  animallist[11],
  animallist[12],
  animallist[13],
  animallist[15],
  animallist[16],
];
List<String> list4 = [
  animallist[0],
  animallist[1],
  animallist[2],
  animallist[3],
  animallist[4],
  animallist[4],
  animallist[5],
  animallist[9],
  animallist[11],
  animallist[14],
];
List<String> list5 = [
  animallist[0],
  animallist[1],
  animallist[2],
  animallist[3],
  animallist[4],
  animallist[5],
  animallist[6],
  animallist[7],
  animallist[8],
  animallist[12],
];
List<String> list6 = [
  animallist[0],
  animallist[1],
  animallist[2],
  animallist[3],
  animallist[4],
  animallist[5],
  animallist[6],
  animallist[7],
  animallist[8],
  animallist[9],
  animallist[10],
];